package dto.response.error;

public enum TypeError {
    RESOURCE_NOT_FOUND(),
    VALIDATION_EXCEPTION,
    DATA_ACCESS_EXCEPTION,
    CONSTRAINT_VIOLATION_EXCEPTION,
    EXCEPTION,
    NOT_FOUND_DATA_EXCEPTION,
    TYPE_HEADER_EXCEPTION
}
